import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { AssetContextProvider } from "@/context/AssetProvider";
import { Sidebar } from "./components/Sidebar/Sidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <div className="w-full flex flex-row custom-scrollbar">
            <Sidebar/>
            <AssetContextProvider> 
                {children}
            </AssetContextProvider>
        </div>
    )
}
