import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import "./styles/globals.css";

import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";
import { AssetContextProvider } from "@/context/AssetProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Navbar />
                <div className="w-full bg-[rgb(5,5,5)]">
                  <AssetContextProvider> 
                    {children}
                  </AssetContextProvider>
                </div>
                <Footer/>
            </body>
        </html>
    )
}
